name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tags:
      - "*"
  repository_dispatch:
    types:
      - build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check new version
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        id: check-tag
        run: |
          tagName="${GITHUB_REF#refs/tags/}"
          if printf '%s' "$tagName" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "tag=$tagName" >>"$GITHUB_OUTPUT"
          fi
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      -
        name: Update version
        if: steps.check-tag.outputs.tag
        run: mvn org.eclipse.tycho:tycho-versions-plugin:set-version "-DnewVersion=${{ steps.check-tag.outputs.tag }}"
      -
        name: Build
        run: mvn -B package --file pom.xml
      -
        name: Copy jar
        if: steps.check-tag.outputs.tag
        run: cp ./target/concrete_cif-*.jar ./concrete-cif.jar
      -
        name: Create release
        if: steps.check-tag.outputs.tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            concrete-cif.jar
            src/main/resources/concrete-cif-1.0.xsd
